name: 'WordPress Plugin SVN Deploy'
description: 'Deploy to the WordPress Plugin Repository'
author: 'xlite-dev'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'upload-cloud'
  color: 'blue'
